/*
 * File: Configs.h
 * Author: Eng_Saad_Redwan
 */

#ifndef APPLICATION_CONFIGS_H_
#define APPLICATION_CONFIGS_H_


#define ON_OFF_BUTTON         BUTTON0
#define ON_OFF_LED            LED0

#define UP_BUTTON             BUTTON1
#define DOWN_BUTTON           BUTTON2

#define HEATING_ELEMENT_REG   DIO_PORTB_REG
#define HEATING_ELEMENT_PIN   DIO_CHANNEL0
#define HEATING_ELEMENT_LED   LED1

#define COOLING_ELEMENT_REG   DIO_PORTB_REG
#define COOLING_ELEMENT_PIN   DIO_CHANNEL1
#define COOLING_ELEMENT_LED   LED2



#endif /* APPLICATION_CONFIGS_H_ */
